#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    background = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    bootstrap_after = "config#after"                                                                                 
    bootstrap_before = "config#before"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "VersionControl"

[[layers]]
name = "checkers"

[[layers]]
name = "ctrlp"

[[layers]]
name = "denite"

[[layers]]
name = "denite"

[[layers]]
name = "fzf"

[[layers]]
name = "git"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#vue"

[[layers]]
name = "sh"

[[layers]]
name = "sudo"

[[layers]]
name = "leaderf"

[[layers]]
name = "lsp"

[[layers]]
name = "tmux"

[[layers]]
name = "tools"

[[layers]]
name = "ui"

[[layers]]
name = "unite"

[[layers]]
name = "lang#plantuml"
